export_attribute_list = [
    'sku', 
    '_store', 
    '_attribute_set',
    '_type', 
    '_category', 
    '_root_category', 
    '_product_websites',        
    'color',
    'cost',
    'country_of_manufacture',
    'created_at',
    'custom_design',
    'custom_design_from',
    'custom_design_to',
    'custom_layout_update',
    'description',
    'enable_googlecheckout',
    'flavor_type',
    'gallery',
    'gift_message_available',
    'has_options',
    'image',
    'image_label',
    'manufacturer',
    'media_gallery',
    'meta_description',
    'meta_keyword',
    'meta_title', 
    'minimal_price',
    'msrp',
    'msrp_display_actual_price_type',
    'msrp_enabled',
    'name',
    'news_from_date',
    'news_to_date',
    'options_container',
    'page_layout',
    'price',
    'required_options',
    'short_description',
    'small_image',
    'small_image_label',
    'special_from_date',
    'special_price',
    'special_to_date',
    'status',
    'tax_class_id',
    'thumbnail',
    'thumbnail_label',
    'updated_at',
    'url_key',
    'url_path',
    'visibility',
    'weight',
    'qty',
    'min_qty',
    'use_config_min_qty',
    'is_qty_decimal',
    'backorders',
    'use_config_backorders',
    'min_sale_qty',
    'use_config_min_sale_qty',
    'max_sale_qty',
    'use_config_max_sale_qty',
    'is_in_stock',
    'notify_stock_qty',
    'use_config_notify_stock_qty',
    'manage_stock',
    'use_config_manage_stock',
    'stock_status_changed_auto',
    'use_config_qty_increments',
    'qty_increments',
    'use_config_enable_qty_inc',
    'enable_qty_increments',
    'is_decimal_divided',
    '_links_related_sku',
    '_links_related_position',
    '_links_crosssell_sku',
    '_links_crosssell_position',
    '_links_upsell_sku',
    '_links_upsell_position',
    '_associated_sku',
    '_associated_default_qty',
    '_associated_position',
    '_tier_price_website',
    '_tier_price_customer_group',
    '_tier_price_qty',
    '_tier_price_price',
    '_group_price_website',
    '_group_price_customer_group',
    '_group_price_price',
    '_media_attribute_id',
    '_media_image',
    '_media_lable',
    '_media_position',
    '_media_is_disabled',
    ]

constant_export_attributes = {
    '_attribute_set': 'Flavor',
    '_type': 'simple',
    '_root_category': 'Default Category',
    '_product_websites': 'base',
    'country_of_manufacture': 'United States',
    'enable_googlecheckout': '1',
    'has_options': '0',
    'image': '/bottle.jpg',
    'image_label': 'Bottle',
    'msrp_display_actual_price_type': 'Use config',
    'msrp_enabled': 'Use config',
    'options_container': 'Block after Info Column',
    'required_options': '0',
    'small_image': '/bottle.jpg',
    'small_image_label': 'Bottle',
    'status': '1',
    'tax_class_id': '4',
    'thumbnail': '/bottle.jpg',
    'thumbnail_label': 'Bottle',
    'visibility': '4',
    'weight': '4',
    'qty': '100',
    'min_qty': '0',
    'use_config_min_qty': '1',
    'is_qty_decimal': '0',
    'backorders': '0',
    'use_config_backorders': '1',
    'min_sale_qty': '1',
    'use_config_min_sale_qty': '1',
    'max_sale_qty': '0',
    'use_config_max_sale_qty': '1',
    'is_in_stock': '1',
    'use_config_notify_stock_qty': '1',
    'manage_stock': '0',
    'use_config_manage_stock': '1',
    'stock_status_changed_auto': '0',
    'use_config_qty_increments': '1',
    'qty_increments': '0',
    'use_config_enable_qty_inc': '1',
    'enable_qty_increments': '0',
    'is_decimal_divided': '0',
    '_media_attribute_id': '88',
    '_media_image': '/bottle.jpg',
    '_media_lable': 'Bottle',
    '_media_position': '1',
    '_media_is_disabled': '0',
}   

empty_export_dict = {}

for attribute in export_attribute_list:
    empty_export_dict[attribute] = ""
    
base_export_dict = empty_export_dict.copy()
base_export_dict.update(constant_export_attributes)
    
#base_export_dict = dict(empty_export_dict.items() + constant_export_attributes.items())
