# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0021_auto_20200318_1410'),
        ('newqc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivinglog',
            name='manufacturer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.Manufacturer'),
        ),
        migrations.AddField(
            model_name='receivinglog',
            name='supplier_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.Supplier'),
        ),
    ]
