# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newqc', '0002_auto_20200318_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivinglog',
            name='manufacturer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='access.Manufacturer'),
        ),
    ]
