from access.models import Supplier
from newqc.models import RMRetain
        
def populate_receiving_log(year):
    models.ReceivingLog.objects.all().delete()
    for rm in models.RMRetain.objects.filter(date__year=year).extra(select={'receiving_year':'extract(year from date)','receiving_month':'extract(month from date)'}).order_by('receiving_year','receiving_month','r_number'):
        rl = models.ReceivingLog()
        rl.r_number = rm.r_number
        
        rl.pin = rm.pin
        rl.supplier = rm.supplier
        rl.lot = rm.lot
        try:
            i = Ingredient.get_obj_from_softkey(rm.pin)
            rl.description = i.prefixed_name
        except:
            rl.description = "---"
        rl.quantity_of_packages = 0
        rl.package_size = 0
        rl.units = "lbs"
        rl.po_number = 0
        rl.trucking_co = "---"
        rl.kosher_group  = "---"
        rl.save()
        rl.date = rm.date
        rl.save()

def main():
    unknown_supp = Supplier.objects.get(suppliername="?")
    unknown_supp_id = unknown_supp.id
    supplier_map = {
        u'?': unknown_supp_id,
        u'A I Inc': 122,
        u'A.C Humpko': 133,
        u'A.M. Todd': 79,
        u'ABT': 143,
        u'AC Humko':133,
        u'AC Humpco': 133,
        u'AC Humpko': 133,
        u'ACH': 133,
        u'AI Inc': 122,
        u'AI Inc.': 122,
        u'AM Instants': 162,
        u'AM Todd': 79,
        u'Aapear': 44,
        u'Aaper': 44,
        u'Abaco': unknown_supp_id,
        u'Abbaco': unknown_supp_id,
        u'Abco': unknown_supp_id,
        u'Abt': 143,
        u'Accurat': 122,
        u'Accurate': 122,
        u'Accurate Ing': 122,
        u'Achumko': 133,
        u'Adron': 216,
        u'Adron/Flaroma': 216,
        u'Ajinomoto': 12,
        u'Aldrich': 125,
        u'Alfrebo': unknown_supp_id,
        u'Alfrebro': unknown_supp_id,
        u'Am Instants': 162,
        u'Am. Color': 215,
        u'Amer. Inst.': 162,
        u'Amer. Int.': 162,
        u'American': unknown_supp_id,
        u'Ariake': 187,
        u'Atlantic': 126,
        u'BASF': 195,
        u'Bedoukain': 111,
        u'Bedoukian': 111,
        u'Bedukian': 111,
        u'Bell': 22,
        u'Bell Flavors': 22,
        u'Bergie': 4,
        u'Berje': 4,
        u'Beverage HSE': 210,
        u'BioSpringer': 227,
        u'Biospringer': 227,
        u'Blue California Co.': 233,
        u'Brenntag': 36,
        u'Brentag': 36,             
        u'Brntag': 36,
        u'Brown': 105,
        u'C&A': 130,
        u'C+A': 130,
        u'CNI': 135,
        u'Cargill': 142,
        u'Carlson': unknown_supp_id,
        u'Charabot': 28,
        u'Charbot': 28,
        u'Chargill': 142,
        u'Chart': 138,
        u'Chart.': 138,
        u'Chart/Naturex': 138,
        u'Chem Tech': 6,
        u'Clofine': 18,
        u'Costco': unknown_supp_id,
        u'D.H. Litter': 64,
        u'DD Williams': 152,
        u'DSM': unknown_supp_id,
        u'Degussa': 200,
        u'Dehydrates': 207,
        u'Del Val': 1,
        u'Del-Val': 1,
        u'DelVal': 1,
        u'Delval': 1,
        u'Dempsey US Corp': 76,
        u'Diana': 181,
        u'Diana Veg.': 181,
        u'Dougoud': unknown_supp_id,
        u'Eastech': unknown_supp_id,
        u'Elan': 121,
        u'Essex': 40,
        u'Essex Grain': 40,
        u'FDI': 2,
        u'FDI/Adron': 216,
        u'FIS':137,
        u'FIS/Givadan': 137,
        u'FIS/Givaudan': 137,
        u'Fencharome': 47,
        u'Ferminich': 41,
        u'Fis': 137,
        u'Flaroma': 216,
        u'Flavorsavor':  unknown_supp_id,
        u"Fleischman's": 224,
        u'Fleurchem': 52,
        u'Franklin': 148,
        u'Franklin Farms': 148,
        u'Frencharoma': 47,
        u'Frencharome': 47,
        u'Frutarom': 166,
        u'Frutarome': 166,
        u'GE': unknown_supp_id,
        u'Golden Peanut': 234,
        u'Greenwood': unknown_supp_id,
        u'Henningsen': 127,
        u'Henningson': 127,
        u'Hormel': 136,
        u'Horn of Plenth': unknown_supp_id,
        u'Houghton': 20,
        u'Hunter': 32,
        u'I - Mart': 17,
        u'I Mart': 17,
        u'I- Mart': 17,
        u'I-Mart': 17,
        u'I-Mart.': 17,
        u'I.C Inc.': 185,
        u'IC Inc': 185,
        u'IC Inc.': 185,
        u'IC, Inc': 185,              
        u'IDF': 164,
        u'IFF': 88,
        u'IOC': 214,
        u'ISC': 11,
        u'Ing Conn': 185,
        u'Ing. Rec.': 61,
        u'Ingred. Conn.': 185,
        u'Ingred. Res.': 61,
        u'Ingredient': unknown_supp_id,
        u'Ingredient Connections': 185,
        u'Ingredient resources': 61,
        u'IngredientRec.': 61,
        u'Ingredients': unknown_supp_id,
        u'Int. Molasses': 188,
        u'Inter. Puree': unknown_supp_id,
        u'International Oils': 214,
        u'International Oils and Conc.': 214,
        u'JRS': 197,
        u'KIC': 159,
        u'Kalsec': 33,
        u'Kelly': 102,
        u'Kelsec': 33,
        u'Kerry': 139,
        u'Lake States': 82,
        u'Lakeside': 146,
        u'Lallemand Inc.': 98,
        u'MAFO': 183,
        u'MT Thunder': 204,
        u'Malt': 163,
        u'Malt Products': 163,
        u'Malt.': 163,
        u'Mardon': 208,
        u'Mardow': 208,
        u'Master Taste': 132,
        u'Mastertaste': 132,
        u'Meer': unknown_supp_id,
        u'Messex': unknown_supp_id,
        u'Mincing': 173,
        u'Miritz': 231,
        u'Mitsui': 213,
        u'Mizkan': unknown_supp_id,
        u'Momentive': unknown_supp_id,
        u'Moore': unknown_supp_id,
        u'Mt Thunder': 204,
        u'Mt. Thunder': 204,
        u'Natural/Advantage': 174,
        u'Naturex': 138,
        u'Nikken': 55,
        u'OM Ing.': 51,
        u'OSI': 5,
        u'OSI WITCO': 5,
        u'OSI/WITCO': 5,
        u'OSI/Witco': 5,
        u'Ocean Cliff': 37,
        u'Opta': 182,
        u'P.I. Inc.': 63,
        u'PG': unknown_supp_id,
        u'PIX': 95,
        u'PTX': 95,
        u'Penta': 128,
        u'Phaemco': 196,
        u'Pharmco': 196,
        u'Pheonix': 45,
        u'Phoeix': 45,
        u'Phoenix': 45,
        u'Phoinix': 45,
        u'Pix': 95,               
        u'Polarome': 59,
        u'Prime': 63,
        u'Prime Ing.': 63,
        u'Prime Ingredients': 63,
        u'Red Arrow': 31,
        u'Red Arrow.': 31,
        u'Red Mnt.': 186,
        u'Red Mountain': 186,
        u'Red Mountian': 186,
        u'RedArrow': 31,
        u'Resturant Depot': unknown_supp_id,
        u'Rhodia': 85,
        u'Robertet': 29,
        u'Rohdia': 85,
        u'Rothstein': 167,
        u'Ryan': 6,
        u'S.A Carlson': 225,
        u'SA Carlson': 225,
        u'Savory': 180,
        u'Savory Syst.': 180,
        u'Scan': 106,
        u'Scan Am.': 106,
        u'Scan Amer': 106,
        u'Scan Amer.': 106,
        u'Scan America': 106,
        u'Scan. Am.': 106,
        u'ScanAm': 106,
        u'ScanAm.': 106,
        u'Schiff': 236,
        u'Sensient': 73,
        u'Sethness': 27,
        u'Sethress': 27,
        u'Silesia': 218,
        u'Sparrow': 161,
        u'Spray Tek': unknown_supp_id,
        u'Spreda': unknown_supp_id,
        u'Starkay White': unknown_supp_id,
        u'Stepan': 94,
        u'TIC': 10,
        u'Tastee': unknown_supp_id,
        u'Terra': 157,
        u'Terra Nova': 157,
        u'Tic': 10,
        u'Tilley': 46,
        u'Tilly': 46,
        u'Tod Hunter':190,
        u'Todd Hunter': 190,
        u'Todhunter': 190,
        u'Treatt': 203,
        u'V Del': 21,
        u'Vero': 101,
        u'Vigon': 193,
        u'Vinced': unknown_supp_id,
        u'Vita Pakt': 212,
        u'Vita-Pakt': 1212,
        u'WCH': 109,
        u'WHC': 109,
        u'Waussa Paper': unknown_supp_id,
        u'Welch': 109,
        u'Welsh': 109,
        u'Yost': 131,
        u'charabot': 28,
        u'essex': 40,
        u'pix': 95,
        u'red Arrow': 31,
        u"vita-pak't": 212,           
    }
    
    for rmr in RMRetain.objects.all():
        if rmr.supplier in supplier_map:
            print rmr
    return

if __name__ == "__main__":
    main()
