from access.models import Supplier
from newqc.models import RMRetain
        
def populate_receiving_log(year):
    models.ReceivingLog.objects.all().delete()
    for rm in models.RMRetain.objects.filter(date__year=year).extra(select={'receiving_year':'extract(year from date)','receiving_month':'extract(month from date)'}).order_by('receiving_year','receiving_month','r_number'):
        rl = models.ReceivingLog()
        rl.r_number = rm.r_number
        
        rl.pin = rm.pin
        rl.supplier = rm.supplier
        rl.lot = rm.lot
        try:
            i = Ingredient.get_obj_from_softkey(rm.pin)
            rl.description = i.prefixed_name
        except:
            rl.description = "---"
        rl.quantity_of_packages = 0
        rl.package_size = 0
        rl.units = "lbs"
        rl.po_number = 0
        rl.trucking_co = "---"
        rl.kosher_group  = "---"
        rl.save()
        rl.date = rm.date
        rl.save()

def main():
    unknown_supp = Supplier.objects.get(suppliername="?")
    unknown_supp_id = unknown_supp.id
    supplier_map = {
        '?': unknown_supp_id,
        'A I Inc': 122,
        'A.C Humpko': 133,
        'A.M. Todd': 79,
        'ABT': 143,
        'AC Humko':133,
        'AC Humpco': 133,
        'AC Humpko': 133,
        'ACH': 133,
        'AI Inc': 122,
        'AI Inc.': 122,
        'AM Instants': 162,
        'AM Todd': 79,
        'Aapear': 44,
        'Aaper': 44,
        'Abaco': unknown_supp_id,
        'Abbaco': unknown_supp_id,
        'Abco': unknown_supp_id,
        'Abt': 143,
        'Accurat': 122,
        'Accurate': 122,
        'Accurate Ing': 122,
        'Achumko': 133,
        'Adron': 216,
        'Adron/Flaroma': 216,
        'Ajinomoto': 12,
        'Aldrich': 125,
        'Alfrebo': unknown_supp_id,
        'Alfrebro': unknown_supp_id,
        'Am Instants': 162,
        'Am. Color': 215,
        'Amer. Inst.': 162,
        'Amer. Int.': 162,
        'American': unknown_supp_id,
        'Ariake': 187,
        'Atlantic': 126,
        'BASF': 195,
        'Bedoukain': 111,
        'Bedoukian': 111,
        'Bedukian': 111,
        'Bell': 22,
        'Bell Flavors': 22,
        'Bergie': 4,
        'Berje': 4,
        'Beverage HSE': 210,
        'BioSpringer': 227,
        'Biospringer': 227,
        'Blue California Co.': 233,
        'Brenntag': 36,
        'Brentag': 36,             
        'Brntag': 36,
        'Brown': 105,
        'C&A': 130,
        'C+A': 130,
        'CNI': 135,
        'Cargill': 142,
        'Carlson': unknown_supp_id,
        'Charabot': 28,
        'Charbot': 28,
        'Chargill': 142,
        'Chart': 138,
        'Chart.': 138,
        'Chart/Naturex': 138,
        'Chem Tech': 6,
        'Clofine': 18,
        'Costco': unknown_supp_id,
        'D.H. Litter': 64,
        'DD Williams': 152,
        'DSM': unknown_supp_id,
        'Degussa': 200,
        'Dehydrates': 207,
        'Del Val': 1,
        'Del-Val': 1,
        'DelVal': 1,
        'Delval': 1,
        'Dempsey US Corp': 76,
        'Diana': 181,
        'Diana Veg.': 181,
        'Dougoud': unknown_supp_id,
        'Eastech': unknown_supp_id,
        'Elan': 121,
        'Essex': 40,
        'Essex Grain': 40,
        'FDI': 2,
        'FDI/Adron': 216,
        'FIS':137,
        'FIS/Givadan': 137,
        'FIS/Givaudan': 137,
        'Fencharome': 47,
        'Ferminich': 41,
        'Fis': 137,
        'Flaroma': 216,
        'Flavorsavor':  unknown_supp_id,
        "Fleischman's": 224,
        'Fleurchem': 52,
        'Franklin': 148,
        'Franklin Farms': 148,
        'Frencharoma': 47,
        'Frencharome': 47,
        'Frutarom': 166,
        'Frutarome': 166,
        'GE': unknown_supp_id,
        'Golden Peanut': 234,
        'Greenwood': unknown_supp_id,
        'Henningsen': 127,
        'Henningson': 127,
        'Hormel': 136,
        'Horn of Plenth': unknown_supp_id,
        'Houghton': 20,
        'Hunter': 32,
        'I - Mart': 17,
        'I Mart': 17,
        'I- Mart': 17,
        'I-Mart': 17,
        'I-Mart.': 17,
        'I.C Inc.': 185,
        'IC Inc': 185,
        'IC Inc.': 185,
        'IC, Inc': 185,              
        'IDF': 164,
        'IFF': 88,
        'IOC': 214,
        'ISC': 11,
        'Ing Conn': 185,
        'Ing. Rec.': 61,
        'Ingred. Conn.': 185,
        'Ingred. Res.': 61,
        'Ingredient': unknown_supp_id,
        'Ingredient Connections': 185,
        'Ingredient resources': 61,
        'IngredientRec.': 61,
        'Ingredients': unknown_supp_id,
        'Int. Molasses': 188,
        'Inter. Puree': unknown_supp_id,
        'International Oils': 214,
        'International Oils and Conc.': 214,
        'JRS': 197,
        'KIC': 159,
        'Kalsec': 33,
        'Kelly': 102,
        'Kelsec': 33,
        'Kerry': 139,
        'Lake States': 82,
        'Lakeside': 146,
        'Lallemand Inc.': 98,
        'MAFO': 183,
        'MT Thunder': 204,
        'Malt': 163,
        'Malt Products': 163,
        'Malt.': 163,
        'Mardon': 208,
        'Mardow': 208,
        'Master Taste': 132,
        'Mastertaste': 132,
        'Meer': unknown_supp_id,
        'Messex': unknown_supp_id,
        'Mincing': 173,
        'Miritz': 231,
        'Mitsui': 213,
        'Mizkan': unknown_supp_id,
        'Momentive': unknown_supp_id,
        'Moore': unknown_supp_id,
        'Mt Thunder': 204,
        'Mt. Thunder': 204,
        'Natural/Advantage': 174,
        'Naturex': 138,
        'Nikken': 55,
        'OM Ing.': 51,
        'OSI': 5,
        'OSI WITCO': 5,
        'OSI/WITCO': 5,
        'OSI/Witco': 5,
        'Ocean Cliff': 37,
        'Opta': 182,
        'P.I. Inc.': 63,
        'PG': unknown_supp_id,
        'PIX': 95,
        'PTX': 95,
        'Penta': 128,
        'Phaemco': 196,
        'Pharmco': 196,
        'Pheonix': 45,
        'Phoeix': 45,
        'Phoenix': 45,
        'Phoinix': 45,
        'Pix': 95,               
        'Polarome': 59,
        'Prime': 63,
        'Prime Ing.': 63,
        'Prime Ingredients': 63,
        'Red Arrow': 31,
        'Red Arrow.': 31,
        'Red Mnt.': 186,
        'Red Mountain': 186,
        'Red Mountian': 186,
        'RedArrow': 31,
        'Resturant Depot': unknown_supp_id,
        'Rhodia': 85,
        'Robertet': 29,
        'Rohdia': 85,
        'Rothstein': 167,
        'Ryan': 6,
        'S.A Carlson': 225,
        'SA Carlson': 225,
        'Savory': 180,
        'Savory Syst.': 180,
        'Scan': 106,
        'Scan Am.': 106,
        'Scan Amer': 106,
        'Scan Amer.': 106,
        'Scan America': 106,
        'Scan. Am.': 106,
        'ScanAm': 106,
        'ScanAm.': 106,
        'Schiff': 236,
        'Sensient': 73,
        'Sethness': 27,
        'Sethress': 27,
        'Silesia': 218,
        'Sparrow': 161,
        'Spray Tek': unknown_supp_id,
        'Spreda': unknown_supp_id,
        'Starkay White': unknown_supp_id,
        'Stepan': 94,
        'TIC': 10,
        'Tastee': unknown_supp_id,
        'Terra': 157,
        'Terra Nova': 157,
        'Tic': 10,
        'Tilley': 46,
        'Tilly': 46,
        'Tod Hunter':190,
        'Todd Hunter': 190,
        'Todhunter': 190,
        'Treatt': 203,
        'V Del': 21,
        'Vero': 101,
        'Vigon': 193,
        'Vinced': unknown_supp_id,
        'Vita Pakt': 212,
        'Vita-Pakt': 1212,
        'WCH': 109,
        'WHC': 109,
        'Waussa Paper': unknown_supp_id,
        'Welch': 109,
        'Welsh': 109,
        'Yost': 131,
        'charabot': 28,
        'essex': 40,
        'pix': 95,
        'red Arrow': 31,
        "vita-pak't": 212,           
    }
    
    for rmr in RMRetain.objects.all():
        if rmr.supplier in supplier_map:
            print(rmr)
    return

if __name__ == "__main__":
    main()
