from django.conf.urls import url, include
from django.urls import path
from access import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('flavorAPI', views.FlavorView)

urlpatterns = (
    # Example:
    #url(r'^fd/', include('fd.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    path('fdAPI/', include(router.urls)),
    path('testapi/', views.test_api_view),
    # Uncomment the next line to enable the admin:
    url(r'^(?P<flavor_number>\d+)/$', views.ft_review, name='flavor_review'),
    url(r'(?P<flavor_number>\d+)/spec_sheet/$', views.spec_sheet),
    url(r'(?P<flavor_number>\d+)/spec_list/$', views.specification_list),
    url(r'(?P<flavor_number>\d+)/spec_list/edit/(?P<spec_id>\d+)/$', views.edit_spec),
    url(r'(?P<flavor_number>\d+)/spec_list/add/$', views.edit_spec),
    url(r'(?P<flavor_number>\d+)/spec_list/delete/(?P<spec_id>\d+)/$', views.delete_spec),
    url(r'^(?P<flavor_number>\d+)/batch_sheet/$', views.batch_sheet),
    url(r'^(?P<flavor_number>\d+)/formula_info_merge/$', views.formula_info_merge),
    url(r'^(?P<flavor_number>\d+)/recalculate/$', views.recalculate_flavor_view),
    url(r'^(?P<flavor_number>\d+)/batch_sheet/$', views.batch_sheet),
    url(r'^(?P<flavor_number>\d+)/formula_entry/$', views.formula_entry),
    url(r'^(?P<flavor_number>\d+)/print_review/$', views.print_review),
    url(r'^(?P<flavor_number>\d+)/reconcile_specs/$', views.reconcile_specs),
    url(r'^(?P<spec_pk>\d+)/edit_spec/$', views.edit_spec),
    url(r'^experimental/(?P<experimentalnum>\d+)/print_review/$', views.experimental_print_review),
    url(r'^tsr/new/$', views.new_tsr),
    url(r'^tsr/(?P<tsr_number>\d+)/$', views.tsr_review),
    url(r'^tsr/(?P<tsr_number>\d+)/tsr_entry/$', views.tsr_entry),
    url(r'^process_tsrli_update/$', views.process_tsrli_update),
    url(r'^purchase/new/$', views.new_po),
    url(r'^purchase/(?P<po_number>\d+)/$', views.po_review),
    url(r'^purchase/(?P<po_number>\d+)/print/$', views.po_review_print),
    url(r'^purchase/(?P<po_number>\d+)/po_entry/$', views.po_entry),
    url(r'^process_cell_update/$', views.process_cell_update),
    url(r'^process_filter_update/$', views.process_filter_update),
    url(r'^ingredient_autocomplete/$', views.ingredient_autocomplete),
    url(r'^digitized_entry/$', views.digitized_entry),
    url(r'^process_digitized_paste/$', views.process_digitized_paste),
    url(r'^table_to_csv$', views.table_to_csv),
    url(r'^get_ingredient_option_list$', views.get_ingredient_option_list),
    url(r'^db_ops$', views.db_ops),
    url(r'^ingredient_replacer/$', views.ingredient_replacer),
    url(r'^ingredient_replacer_preview/(?P<old_ingredient_id>\d+)/(?P<new_ingredient_id>\d+)/$', views.ingredient_replacer_preview),
    url(r'^location_entry/$', views.location_entry),
    url(r'^$', views.flavor_search),
    url(r'^(?P<flavor_number>\d+)/barcode/$', views.get_barcode),
    url(r'^(?P<flavor_number>\d+)/gzl/$', views.gzl),
    url(r'^ingredient/pin_review/(?P<ingredient_id>\d+)/$', views.ingredient_pin_review),
    url(r'^ingredient/(?P<ingredient_rmc>\d+)/$', views.ingredient_review),
    url(r'^ingredient/pin_review/(?P<ingredient_id>\d+)/gzl/$', views.ingredient_gzl_review),
    url(r'^ingredient/pin_review/(?P<ingredient_id>\d+)/documentation/$', views.ingredient_documentation),
    url(r'^ingredient/activate/(?P<raw_material_code>\d+)/$', views.ingredient_activate),
    url(r'^ingredient/activate/discontinue_all/(?P<ingredient_id>\d+)/$', views.ingredient_activate),
    url(r'^ingredient/rm_inventory_data_entry/$', views.rm_inventory_data_entry),
    url(r'^ingredient/get_ingredient_name/$', views.get_ingredient_name),
    url(r'^experimental/(?P<experimentalnum>\d+)/formula_entry/$', views.experimental_formula_entry),
    url(r'^experimental/(?P<experimentalnum>\d+)/$', views.experimental_review),
    url(r'^experimental/(?P<experimentalnum>\d+)/recalculate/$', views.recalculate_experimental),
    url(r'^experimental/(?P<experimentalnum>\d+)/approve/$', views.approve_experimental),
    url(r'^experimental/(?P<experimentalnum>\d+)/edit/$', views.experimental_edit),
    url(r'^experimental/(?P<experimentalnum>\d+)/name_edit/$', views.experimental_name_edit),
    url(r'^experimental/(?P<experimentalnum>\d+)/add_formula/$', views.experimental_add_formula),
    url(r'^digitized/(?P<experimentalnum>\d+)/$', views.digitized_review),
    url(r'^ft/(?P<flavor_number>\d+)/$', views.ft_review),
    url(r'^ajax_dispatch/$', views.ajax_dispatch),
    url(r'^similar/$', views.jil_object_list),
    url(r'^new_ex/$', views.new_ex_wizard),
    url(r'^new_rm/$', views.new_rm_wizard_launcher),
    url(r'^new_rm/basic/$', views.new_rm_wizard),
    url(r'^new_rm/solution_starter/$', views.new_solution_starter),
    url(r'^new_rm/solution_wizard/pin=(?P<PIN>\d+)/solv=(?P<solvent>\d+)/conc=(?P<concentration>\d+(?:\.\d+)?)/$', views.new_solution_wizard),
    url(r'^new_rm/flavor/(?P<flavor_number>\d+)/$', views.new_rm_wizard_flavor),
    url(r'^new_rm/rm/(?P<ingredient_pk>\d+)/$', views.new_rm_wizard_rm),
    url(r'^allergen_list/$', views.allergen_list),
    url(r'^rm_allergen_list/$', views.rm_allergen_list),
    # url(r'^angularjs_test/$', views.angularjs_test),
    url(r'^unique_hazard_combinations/$', views.unique_hazard_combinations),
    url(r'^ingredient_hazard_report/$', views.ingredient_hazard_report),
    url(r'^flavor_hazard_report/$', views.flavor_hazard_report),
    url(r'^small_flavor_hazard_label/(?P<flavor_number>\d+)/$', views.small_flavor_hazard_label),
    url(r'^outdated_raw_materials/$', views.outdated_raw_material_list),
    url(r'^missing_cas_numbers/$', views.missing_cas_numbers),
    url(r'^cas_number_discrepancies/$', views.cas_number_discrepancies),
    url(r'^ingredient_statement/$', views.ingredient_statement),
    url(r'^ingredient_statement/(?P<flavor_number>\d+)/$', views.ingredient_statement_review),
    url(r'^ingredient_statement/(?P<flavor_number>\d+)/edit/$', views.ingredient_statement_edit),
    url(r'^active_purchase_orders/$', views.active_purchase_orders),
    url(r'^purchase_orders_within_one_year/$', views.purchase_orders_within_one_year),
    url(r'^purchase_orders/(?P<po_number>\d+)/$', views.purchase_order_review),
    url(r'^purchase_orders/(?P<po_number>\d+)/edit/(?P<poli_pk>\d+)$', views.receiving_log_edit),
    url(r'^rm_nutri_edit/$', views.rm_nutri_edit),
    url(r'^flavor_nutri_facts/(?P<flavor_number>\d+)/$', views.flavor_nutri_facts),
    url(r'^flavor_nutri_facts/$', views.flavor_nutri_facts),
    url(r'^allergen_declaration/(?P<flavor_number>\d+)/$', views.allergen_declaration),
    url(r'^gmo_statement/(?P<flavor_number>\d+)/$', views.gmo_statement),
    url(r'^product_spec_sheet/(?P<flavor_number>\d+)/$', views.product_spec_sheet),
    url(r'^one_off_specs/$', views.one_off_specs),
    url(r'^one_off_specs/(?P<flavor_number>\d+)/$', views.one_off_specs),
    url(r'^renumber/(?P<flavor_number>\d+)/$', views.renumber),
    url(r'^document_control/(?P<pin_number>\d+)/$', views.document_control, {'rm_code':-1, 'doctype': None}),
    url(r'^document_control/(?P<pin_number>\d+)/(?P<rm_code>\d+)/$', views.document_control, {'doctype': None}),
    url(r'^document_control/(?P<pin_number>\d+)/(?P<rm_code>\d+)/(?P<doctype>\w+)/$', views.document_control),
    url(r'^document_verification/$', views.document_verification, {'doc_id':None}),
    url(r'^document_verification/(?P<doc_id>\d+)/$', views.document_verification),
    url(r'^dv_autocomplete/$', views.dv_autocomplete),
    url(r'^mass_upload/$', views.mass_upload),
    url(r'^flavor_copier/$', views.flavor_copier),
    url(r'^training/$', views.training),
    url(r'^gbpp/$', views.glass_and_brittle),
    url(r'^osha/$', views.osha_lockout),
    url(r'^wiki/$', views.wiki_review),
    url(r'^admin_certification/$', views.admin_certification),
    url(r'^admin_individual_training/$', views.admin_individual_training),
    url(r'^colorblind/$', views.color_blind),
    url(r'^fooddefense/$', views.food_defense),
    url(r'^ccp/$', views.ccp_allergen),
    url(r'^handbook/$', views.employee_handbook),
    url(r'^food_safety/$', views.food_safety, {'section':''}),
    url(r'^food_safety/(?P<section>\w+)/$', views.food_safety),
    url(r'^fltv/$', views.fork_lift_video),
    url(r'^wpsafety/$', views.workplace_safety),
    url(r'^hazcom/$', views.hazcom),
    url(r'^training_overview/$', views.training_overview, {'username':None}),
    url(r'^training_overview/(?P<username>\w+)/$', views.training_overview),
    url(r'^json_test_response/(?P<flavor_number>\d+)/$', views.json_test_response),
    url(r'^docreview_comparison/(?P<document_id>\d+)/$', views.docreview_comparison),

    # url(r'^document_verification/(?P<doc_id>\d+)/$', views.document_verification),



    url(r'^ingredient_comparison_reports/$', views.ingredient_comparison_reports),
    url(r'^upload_cas_fema/$', views.upload_cas_fema),
    url(r'^preview_cas_fema/$', views.preview_cas_fema),
    url(r'^success_cas_fema/$', views.success_cas_fema),
    url(r'^ingredient_hazard_report/$', views.ingredient_hazard_report),
    url(r'^flavor_hazard_report/$', views.flavor_hazard_report),
    url(r'^small_flavor_hazard_label/(?P<flavor_number>\d+)/$', views.small_flavor_hazard_label),
    url(r'^safety_data_sheet/(?P<flavor_number>\d+)/$', views.flavor_sds),
    url(r'^flavor_hazard_details/(?P<flavor_number>\d+)/$', views.flavor_hazard_details),
    url(r'^unique_hazard_combinations/$', views.unique_hazard_combinations),
    url(r'^coa/(?P<lot_number>\d+)/$', views.coa),
    url(r'^query_list/$', views.query_list),
    url(r'^shipping_suggestions/$', views.shipping_suggestions),

)
