# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-25 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_type',
        ),
    ]
