# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-25 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_remove_question_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_type',
            field=models.CharField(choices=[(b'gbpp', b'Glass and Brittle Plastic Policy'), (b'wiki', b'Wiki Review'), (b'hazcom', b'Hazcom 2012 SDS Training'), (b'handbook', b'Employee Handbook Confirmation'), (b'colorblind', b'Color Blind Test'), (b'fooddefense', b'Food Defense Plan Training'), (b'facemask', b'Face Mask Fit Test'), (b'sensory', b'Sensory Evaluation Training'), (b'ccp', b'CCP and Allergen HACCP Questionaire'), (b'osha', b'OSHA Lockout Tagout'), (b'firedrill', b'Fire Drill'), (b'fltv', b'Forklift Training Video'), (b'fltdt', b'Forklift Drivers Test'), (b'wpsafety', b'Workplace Safety'), (b'bacteria', b'Bacteria Review'), (b'foodborne', b'Foodborne Illness Review'), (b'personalhygiene', b'Personal Hygiene Review'), (b'haccp', b'HACCP Review'), (b'sanitation', b'Sanitation Review'), (b'time', b'Time and Temperature Controls Review'), (b'foreign', b'Foreign Material Detection Review'), (b'cross', b'Cross Contamination Review'), (b'allergens', b'Allergens Review'), (b'pest', b'Pest Control Review'), (b'security', b'Security Review'), (b'survey', b'Food Safety Survey')], default=b'', max_length=30),
        ),
    ]
