# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_question_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='spanish_version',
            field=models.BooleanField(default=False),
        ),
    ]
