# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-25 13:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access', '0014_auto_20200225_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default=b'', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[(b'gbpp', b'Glass and Brittle Plastic Policy'), (b'wiki', b'Wiki Review'), (b'hazcom', b'Hazcom 2012 SDS Training'), (b'handbook', b'Employee Handbook Confirmation'), (b'colorblind', b'Color Blind Test'), (b'fooddefense', b'Food Defense Plan Training'), (b'facemask', b'Face Mask Fit Test'), (b'sensory', b'Sensory Evaluation Training'), (b'ccp', b'CCP and Allergen HACCP Questionaire'), (b'osha', b'OSHA Lockout Tagout'), (b'firedrill', b'Fire Drill'), (b'fltv', b'Forklift Training Video'), (b'fltdt', b'Forklift Drivers Test'), (b'wpsafety', b'Workplace Safety'), (b'bacteria', b'Bacteria Review'), (b'foodborne', b'Foodborne Illness Review'), (b'personalhygiene', b'Personal Hygiene Review'), (b'haccp', b'HACCP Review'), (b'sanitation', b'Sanitation Review'), (b'time', b'Time and Temperature Controls Review'), (b'foreign', b'Foreign Material Detection Review'), (b'cross', b'Cross Contamination Review'), (b'allergens', b'Allergens Review'), (b'pest', b'Pest Control Review'), (b'security', b'Security Review'), (b'survey', b'Food Safety Survey')], default=b'', max_length=30)),
                ('question', models.CharField(default=b'', max_length=500)),
                ('answer_options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=b'', max_length=2000), blank=True, default=[], null=True, size=None)),
                ('spanish_version', models.BooleanField(default=False)),
                ('correct_answer', models.CharField(default=b'', max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='access.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
