# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0017_auto_20200303_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='spanish_version',
            field=models.BooleanField(default=False),
        ),
    ]
