# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-18 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0020_swap_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.Supplier'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='suppliers',
            field=models.ManyToManyField(to='access.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.Supplier'),
        ),
    ]
