# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0022_auto_20200325_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='access.Manufacturer'),
        ),
    ]
