# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-22 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0026_auto_20200422_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='description',
        ),
        migrations.RemoveField(
            model_name='specsheetinfo',
            name='description',
        ),
    ]
